name: spotify
description: "Spotify Clone - Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # ðŸ”Š Audio Player
  just_audio: ^0.10.5

  # ðŸŒ HTTP API Calls
  http: ^1.3.0

  # ðŸ”— URL Launcher for sharing links
  url_launcher: ^6.1.10

  # ðŸ“¤ Share functionality
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/spotify_logo.png
    - assets/images/kpop_collage.png
    - assets/images/logo.png
    - assets/icons/apple.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/twitter.png
    - assets/icons/whtsapp.png
    - assets/icons/link.png
    - assets/icons/more.png
    - assets/images/default.png
