name: spotify
description: "Spotify Clone - Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1

  # ðŸ”Š Audio Player
  just_audio: ^0.9.36

  # ðŸŒ HTTP API Calls
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/spotify_logo.png
    - assets/images/kpop_collage.png
    - assets/images/logo.png
    - assets/icons/apple.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/images/default.png
